{{- if not .Values.fortiaigate.env.csrfSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fortiaigate.fullname" . }}-csrf
  namespace: {{ include "fortiaigate.namespace" . }}
  labels:
    {{- include "fortiaigate.labels" . | nindent 4 }}
type: Opaque
data:
  csrf-secret-key: {{ (randAlphaNum 32) | b64enc | quote }}
{{- end }}