{{- if and (or .Values.tls.enabled .Values.postgresql.tls.enabled .Values.redis.tls.enabled) (not .Values.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fortiaigate.tlsSecretName" . }}
  labels:
    app.kubernetes.io/name: fortiaigate
    app.kubernetes.io/part-of: fortiaigate-platform
    app.kubernetes.io/managed-by: helm
type: kubernetes.io/tls
data:
  tls.crt: {{ tpl (.Files.Get .Values.tls.cert) $ | b64enc }}
  tls.key: {{ tpl (.Files.Get .Values.tls.key) $ | b64enc }}
{{- end }}
